spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

provider:
  youtube:
    url: "https://www.youtube.com/oembed?url="

  twitter:
    url: "https://publish.twitter.com/oembed?url="

  vimeo:
    url: "https://vimeo.com/api/oembed.json?url="

  instagram:
    url: "https://graph.facebook.com/v10.0/instagram_oembed?url="

oembed:
  instagram:
    accessToken: "Fail to Receive accessToken"